export const languages = [
  {
    id: 1,
    languageName: 'SQL',
    yearOfStart: '1970',
    Creator: 'Donald D. Chamberlin, Raymond F. Boyce',
    useCase: ['Database management'],
  },
  {
    id: 2,
    languageName: 'C',
    yearOfStart: '1972',
    Creator: 'Dennis Ritchie',
    useCase: ['System programming', 'embedded systems'],
  },
  {
    id: 3,
    languageName: 'C++',
    yearOfStart: '1983',
    Creator: 'Bjarne Stroustrup',
    useCase: ['Game development', 'system software'],
  },
  {
    id: 4,
    languageName: 'Perl',
    yearOfStart: '1987',
    Creator: 'Larry Wall',
    useCase: ['Scripting', 'web development', 'automation'],
  },
  {
    id: 5,
    languageName: 'HTML',
    yearOfStart: '1991',
    Creator: 'Tim Berners-Lee',
    useCase: ['Web content structure'],
  },
  {
    id: 6,
    languageName: 'Python',
    yearOfStart: '1991',
    Creator: 'DGuido van Rossum',
    useCase: ['Web development', ' data analysis', ' AI'],
  },
  {
    id: 7,
    languageName: 'Java',
    yearOfStart: '1995',
    Creator: 'James Gosling',
    useCase: ['Enterprise software', 'Android apps'],
  },
  {
    id: 8,
    languageName: 'JavaScript',
    yearOfStart: '1995',
    Creator: 'Brendan Eich',
    useCase: ['Web development', 'browser scripting'],
  },
  {
    id: 9,
    languageName: 'PHP',
    yearOfStart: '1995',
    Creator: 'Rasmus Lerdorf',
    useCase: ['Web development', 'server-side scripting'],
  },
  {
    id: 10,
    languageName: 'CSS',
    yearOfStart: '1996',
    Creator: 'Håkon Wium Lie, Bert Bos',
    useCase: ['Web page styling'],
  },
  {
    id: 11,
    languageName: 'C#',
    yearOfStart: '2000',
    Creator: 'Microsoft',
    useCase: ['Windows apps', 'game development'],
  },
  {
    id: 12,
    languageName: 'Scala',
    yearOfStart: '2003',
    Creator: 'Martin Odersky',
    useCase: ['Web applications', 'data analysis'],
  },
  {
    id: 13,
    languageName: 'Golang',
    yearOfStart: '2009',
    Creator: 'Robert Griesemer, Rob Pike, Ken Thompson',
    useCase: ['Cloud computing', 'microservices'],
  },
  {
    id: 14,
    languageName: 'Rust',
    yearOfStart: '2010',
    Creator: 'Graydon Hoare',
    useCase: ['Systems programming', 'safety'],
  },
  {
    id: 15,
    languageName: 'Kotlin',
    yearOfStart: '2011',
    Creator: 'JetBrains',
    useCase: ['Android app development', 'server-side'],
  },
  {
    id: 16,
    languageName: 'Swift',
    yearOfStart: '2014',
    Creator: 'Apple Inc.',
    useCase: ['iOS', 'macOS app development'],
  },
];
